{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appLabel }}-sm
  namespace: {{ .Values.monitoring.serviceMonitor.namespace | default "monitoring" }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}-web
  endpoints:
    - port: {{ .Values.monitoring.serviceMonitor.portName | default "http" }}
      path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "5s" }}
{{- end }}
