apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.appLabel}}-secrets
  namespace: {{.Values.namespace}}
type: {{.Values.secrets.type}}
stringData:
  SECRET_KEY: {{ .Values.secrets.stringData.SECRET_KEY | quote }}
  DB_PASSWORD: {{.Values.secrets.stringData.DB_PASSWORD}}
  DB_USER: {{.Values.secrets.stringData.DB_USER}}