apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appLabel}}-configmap
  namespace: {{.Values.namespace }}
  labels:
    app: {{.Values.appLabel}}
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
