apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful-set
  namespace: db-ns
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: mysql-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db-container
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql-database
        envFrom:
        - secretRef:
            name: mysql-db-secrets
        volumeMounts:
        - name: user-data
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
          initialDelaySeconds: 30 
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: mysql-init-script
        configMap:
          name: mysql-db-configmap
  volumeClaimTemplates:
  - metadata:
      name: user-data
    spec:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

