apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secrets
  namespace: db-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGV2cGFzc3dvcmQxMjM=
  MYSQL_USER: YXBwX3VzZXI=  
  MYSQL_PASSWORD: ZGV2cGFzc3dvcmQxMjM=
  MYSQL_DATABASE: YXBwX2Ri